" -- global config --
syntax on
filetype plugin indent on
set cursorline
set ruler
set number
set expandtab
set nowrap
set noswapfile

" -- make fold views automatic --
autocmd BufWinLeave *.* mkview!
autocmd BufWinEnter *.* silent loadview

" -- html config --
autocmd BufNewFile *.html 0r ~/.vim/skeleton/skeleton.html
let g:user_emmet_leader_key=','

" -- py config --
autocmd BufNewFile *.py 0r ~/.vim/skeleton/skeleton.py

" -- sh config --
autocmd BufNewFile *.sh 0r ~/.vim/skeleton/skeleton.sh

" -- md config --
autocmd BufNewFile *.sh 0r ~/.vim/skeleton/skeleton.md
